"C, H, N, S, O = 12.011, 1.008, 14.007, 32.065, 15.999"  
"n_C, n_H, n_N, n_S, n_O = 9, 15, 1, 1, 4"  
"MW = n_C*C + n_H*H + n_N*N + n_S*S + n_O*O"  
"print(f"C9H15NúSO4")"  
"print(f"  C:  {n_C} x {C} = {n_C*C}")"  
"print(f"  H:  {n_H} x {H} = {n_H*H}")"  
"print(f"  N:  {n_N} x {N} = {n_N*N}")"  
"print(f"  S:  {n_S} x {S} = {n_S*S}")"  
"print(f"  O:  {n_O} x {O} = {n_O*O}")"  
"print(f"MW = {MW:.2f} g/mol")"  
